spring.application.name=FuelTrack
spring.main.lazy-initialization=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fueltrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fueltrack}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fueltrack}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.security.user.name=disabled
spring.security.user.password=disabled

app.jwt.secret=change-me-change-me-change-me-change-me-change-me
app.jwt.expiration-ms=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

app.fulfillment.geofence.center-lat=-12.046374
app.fulfillment.geofence.center-lng=-77.042793
app.fulfillment.geofence.radius-meters=5000

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:8080,https://fueltrack-28dba.web.app,https://fueltrack-28dba.firebaseapp.com,https://fueltrack-frontend-web.onrender.com}